In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\jency\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jency\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\jency\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\jency\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 624.1 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/9.8 MB 710.9 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/9.8 MB 710.9 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.8 MB 745.5 kB/s eta 0:00:12
   ---- ----------------------------------- 1.0/9.8 MB 745.5 kB/s eta 0:00:12
   ------ --------------------------------- 1.6/9.8 MB 832.9 kB/s eta 0:00:10
   ------- -------------------------------- 1.8/9.8 MB 891.7 kB/s eta 0:00:09
   ------- -------------------------------- 1.8/9.8 MB 891.7 kB/s eta 0:00:09
   -------- ------------------------------- 2.1/9.8 MB 846.5 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/9.8 MB 893.7 kB/s eta 0:00:09
   ---------- ----------------------------- 2.6/9.8 MB 890.5 kB/s eta 0:00:09
   ---------- ----------------------------- 2.6/9.8 MB 890.5 kB/s eta 0:00:09
   ----------- ---------------------------- 2.9/9.8 MB 851.1 kB/s eta 0:00:09
   ----------- ---------------------------- 2.9/9.8 MB 851.1 kB/s eta 0:00:09
   ------------ --------------------------- 3.1/9.8 MB 828.1 kB/s eta 0:00:09
   ------------ --------------------------- 3.1/9.8 MB 828.1 kB/s eta 0:00:09
   ------------- -------------------------- 3.4/9.8 MB 823.6 kB/s eta 0:00:08
   ------------- -------------------------- 3.4/9.8 MB 823.6 kB/s eta 0:00:08
   -------------- ------------------------- 3.7/9.8 MB 822.9 kB/s eta 0:00:08
   ---------------- ----------------------- 3.9/9.8 MB 833.7 kB/s eta 0:00:08
   ----------------- ---------------------- 4.2/9.8 MB 833.8 kB/s eta 0:00:07
   ------------------ --------------------- 4.5/9.8 MB 870.8 kB/s eta 0:00:07
   -------------------- ------------------- 5.0/9.8 MB 916.3 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.8 MB 916.3 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.8 MB 916.3 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.8 MB 916.3 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.8 MB 840.6 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.8 MB 840.6 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.8 MB 840.6 kB/s eta 0:00:06
   ---------------------- ----------------- 5.5/9.8 MB 803.7 kB/s eta 0:00:06
   ---------------------- ----------------- 5.5/9.8 MB 803.7 kB/s eta 0:00:06
   ----------------------- ---------------- 5.8/9.8 MB 795.0 kB/s eta 0:00:06
   ----------------------- ---------------- 5.8/9.8 MB 795.0 kB/s eta 0:00:06
   ------------------------ --------------- 6.0/9.8 MB 788.2 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 788.2 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 788.2 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 753.3 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 753.3 kB/s eta 0:00:05
   -------------------------- ------------- 6.6/9.8 MB 747.1 kB/s eta 0:00:05
   -------------------------- ------------- 6.6/9.8 MB 747.1 kB/s eta 0:00:05
   -------------------------- ------------- 6.6/9.8 MB 747.1 kB/s eta 0:00:05
   --------------------------- ------------ 6.8/9.8 MB 719.7 kB/s eta 0:00:05
   --------------------------- ------------ 6.8/9.8 MB 719.7 kB/s eta 0:00:05
   --------------------------- ------------ 6.8/9.8 MB 719.7 kB/s eta 0:00:05
   --------------------------- ------------ 6.8/9.8 MB 719.7 kB/s eta 0:00:05
   ---------------------------- ----------- 7.1/9.8 MB 688.7 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.8 MB 688.7 kB/s eta 0:00:04
   ----------------------------- ---------- 7.3/9.8 MB 687.5 kB/s eta 0:00:04
   ----------------------------- ---------- 7.3/9.8 MB 687.5 kB/s eta 0:00:04
   ------------------------------- -------- 7.6/9.8 MB 685.3 kB/s eta 0:00:04
   -------------------------------- ------- 7.9/9.8 MB 694.1 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.8 MB 694.1 kB/s eta 0:00:03
   --------------------------------- ------ 8.1/9.8 MB 702.0 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.8 MB 706.0 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.8 MB 738.0 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.8 MB 743.1 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 750.9 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 750.9 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 750.9 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 737.3 kB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 733.6 kB/s  0:00:13
Installing collected packages: pandas
Successfully installed pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd
data={"product":["A","B","C","D"],
      "sales":[1000,2000,3000,4000],
      "profit":[200,150,300,700]}
df=pd.DataFrame(data)
print("\nsample DataFrame")
display(df)


data ={"reg_no":[101,102,103,104,105,106,107],
      "Name" :["jency","beyana","chicku","manisha","pinky","mano","achu"],
      "marks" :[98,63,100,35,85,85,96]}
df=pd.DataFrame(data)
print("\nsample DataFrame")
print(df["Name"])
display(df)

data={"state":["Tamilnadu","kerala","madurai","salem"],
      "famous" :["kanniyakumari beech","putu&palam","malai","mango"],
      "language" :["Tamil","Malayalam","Tamil","Tamil"],
      "population" :[8.4, 3.9, 2.7,4.5]}
df=pd.DataFrame(data)
print("\n sample DataFrame")
display(df)

sample DataFrame

  product  sales  profit
0       A   1000     200
1       B   2000     150
2       C   3000     300
3       D   4000     700

sample DataFrame

   reg_no     Name  marks
0     101    jency     98
1     102   beyana     63
2     103   chicku    100
3     104  manisha     35
4     105    pinky     85
5     106     mano     85
6     107     achu     96

In [22]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
titanic = pd.read_csv(url)
print("\nTitanic dataset:")
display(titanic)

Titanic dataset:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [26]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
titanic = pd.read_csv(url)
titanic[:35]
titanic["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [49]:

import numpy as np
pd.date_range("20260101",periods=6,freq='MS')
date=pd.date_range("20260101",periods=6)
df=pd.DataFrame(np.random.randn(6,4) , index=date, columns=list("ABCD"))
display(df)

pd.date_range("20230101",periods=6,freq='YS')
dates=pd.date_range("20230101",periods=6)
df=pd.DataFrame(np.random.randn(6,5),index=date, columns=list("ABCDE"))
display(df)

                   A         B         C         D
2026-01-01  0.110964 -0.505878  2.212804 -0.265496
2026-01-02  0.155722  0.094991  3.126473 -0.501187
2026-01-03 -0.338393 -0.527563  1.356328  1.235310
2026-01-04  0.573782  0.328293 -0.399574  0.267513
2026-01-05 -0.847892 -0.019115 -0.973624 -1.651464
2026-01-06 -0.057215 -0.553400  0.236976  0.473564

                   A         B         C         D         E
2026-01-01  0.783962  0.537174 -1.944606  0.872707  0.426243
2026-01-02 -0.035987 -0.856442 -0.757075 -1.274816 -0.497683
2026-01-03 -1.330482 -0.952530  0.582216 -1.207622  0.086496
2026-01-04  0.201969  0.686239  1.125890  1.604602 -0.076805
2026-01-05  0.501774 -0.431755  1.088516 -1.988447  0.833174
2026-01-06 -0.111241 -0.175500 -2.379272 -0.007422  0.536189

In [81]:
#data cleaning
import pandas as pd 
data={"Name":["jency","joyeelin","pinky",None,"mano","akshay","ugin"],
      "age":[21,25,25,None,29,28,30],
      "salary":[45000,50000,None,46000,12000,45000,90000],
      "department":["HR","AI",None,"EEE","HR","ML","HM"]}
employees=pd.DataFrame(data)
print("original data")
display(employees)

print("\n missing value:")
display(employees.isna())
display(employees.isna().sum())

clean_df=employees.copy()
clean_df["age"]=clean_df["age"].fillna(clean_df["age"].mean())
display(clean_df)

clean_df.dropna(subset=["Name","department"],inplace= True)
clean_df.drop_duplicates(inplace=True)
print("\ncleaned data:")
display(clean_df)

original data

       Name   age   salary department
0     jency  21.0  45000.0         HR
1  joyeelin  25.0  50000.0         AI
2     pinky  25.0      NaN        NaN
3       NaN   NaN  46000.0        EEE
4      mano  29.0  12000.0         HR
5    akshay  28.0  45000.0         ML
6      ugin  30.0  90000.0         HM

 missing value:

    Name    age  salary  department
0  False  False   False       False
1  False  False   False       False
2  False  False    True        True
3   True   True   False       False
4  False  False   False       False
5  False  False   False       False
6  False  False   False       False

Name          1
age           1
salary        1
department    1
dtype: int64

       Name        age   salary department
0     jency  21.000000  45000.0         HR
1  joyeelin  25.000000  50000.0         AI
2     pinky  25.000000      NaN        NaN
3       NaN  26.333333  46000.0        EEE
4      mano  29.000000  12000.0         HR
5    akshay  28.000000  45000.0         ML
6      ugin  30.000000  90000.0         HM

cleaned data:

       Name   age   salary department
0     jency  21.0  45000.0         HR
1  joyeelin  25.0  50000.0         AI
4      mano  29.0  12000.0         HR
5    akshay  28.0  45000.0         ML
6      ugin  30.0  90000.0         HM

In [11]:
import pandas as pd
data={"Chocolate": ["milkybar","dairy milk",None,"snickers"],
      "products":["milk product","dairyproduct","milk product",None],
      "Rate":[10-500,10-500,None,10-500,]}
df=pd.DataFrame(data)
display(df)
print(df["Chocolate"])
display(df)

    Chocolate      products   Rate
0    milkybar  milk product -490.0
1  dairy milk  dairyproduct -490.0
2         NaN  milk product    NaN
3    snickers           NaN -490.0

0      milkybar
1    dairy milk
2           NaN
3      snickers
Name: Chocolate, dtype: str

    Chocolate      products   Rate
0    milkybar  milk product -490.0
1  dairy milk  dairyproduct -490.0
2         NaN  milk product    NaN
3    snickers           NaN -490.0

In [21]:
#DATA MANIPULATION
import pandas as pd
import numpy as np
# create sample dataframe
sales=pd.DataFrame({
    "Date":pd.date_range("2026-10-13",periods=10),
    "product":np.random.choice(["Widget", "Gadget", "Tool"],10),
    "units":np.random.randint(1,20,10),
    "unit_price":np.random.uniform(10,50,10).round(2)
        })
sales

        Date product  units  unit_price
0 2026-10-13  Gadget      6       33.97
1 2026-10-14  Widget     15       10.44
2 2026-10-15  Widget      7       23.43
3 2026-10-16  Widget      3       25.38
4 2026-10-17  Widget      6       45.87
5 2026-10-18  Widget      4       28.29
6 2026-10-19    Tool     11       17.13
7 2026-10-20    Tool      5       27.19
8 2026-10-21  Widget      8       15.70
9 2026-10-22    Tool     14       13.61

In [20]:
sales["Total"]=sales["units"]*sales["unit_price"]
print("sales data with total")
display(sales)

sales data with total

        Date product  units  unit_price   Total
0 2026-10-13  Gadget     18       14.53  261.54
1 2026-10-14    Tool     19       17.36  329.84
2 2026-10-15  Gadget     12       36.65  439.80
3 2026-10-16  Widget      6       46.94  281.64
4 2026-10-17    Tool      2       48.85   97.70
5 2026-10-18  Widget     14       12.30  172.20
6 2026-10-19    Tool      4       13.85   55.40
7 2026-10-20  Widget     19       10.01  190.19
8 2026-10-21    Tool     12       24.81  297.72
9 2026-10-22    Tool      6       15.67   94.02

In [23]:
#applying lambda function
sales["price_category"]=sales["unit_price"].apply(
    lambda x :"HIGH" if x>25 else "LOW")
print("\n with price_category")
display(sales)

 with price_category

        Date product  units  unit_price price_category
0 2026-10-13  Gadget      6       33.97           HIGH
1 2026-10-14  Widget     15       10.44            LOW
2 2026-10-15  Widget      7       23.43            LOW
3 2026-10-16  Widget      3       25.38           HIGH
4 2026-10-17  Widget      6       45.87           HIGH
5 2026-10-18  Widget      4       28.29           HIGH
6 2026-10-19    Tool     11       17.13            LOW
7 2026-10-20    Tool      5       27.19           HIGH
8 2026-10-21  Widget      8       15.70            LOW
9 2026-10-22    Tool     14       13.61            LOW

In [38]:
#binning
sales["unit_Bin"]=pd.cut(
    sales["units"],
    bins=[0,5,10,20,30],
    labels=["LOW","MEDIUM" ,"HIGH","VERY HIGH"],
    include_lowest=True
)
print("\n with binned units")
display(sales)

 with binned units

        Date product  units  unit_price price_category unit_Bin
0 2026-10-13  Gadget      6       33.97           HIGH   MEDIUM
1 2026-10-14  Widget     15       10.44            LOW     HIGH
2 2026-10-15  Widget      7       23.43            LOW   MEDIUM
3 2026-10-16  Widget      3       25.38           HIGH      LOW
4 2026-10-17  Widget      6       45.87           HIGH   MEDIUM
5 2026-10-18  Widget      4       28.29           HIGH      LOW
6 2026-10-19    Tool     11       17.13            LOW     HIGH
7 2026-10-20    Tool      5       27.19           HIGH      LOW
8 2026-10-21  Widget      8       15.70            LOW   MEDIUM
9 2026-10-22    Tool     14       13.61            LOW     HIGH

In [67]:
#testing
data ={"reg_no":[101,102,103,104,105,106,107],
      "Name" :["jency","beyana","chicku","manisha","pinky","mano","achu"],
      "marks" :[98,63,100,35,85,85,96]}
df=pd.DataFrame(data)
display(df)
display(df.head(3))
display(df.tail(2))
display(df.shape)
display(df.columns)
display(df["marks"])
display(df["Name"])

   reg_no     Name  marks
0     101    jency     98
1     102   beyana     63
2     103   chicku    100
3     104  manisha     35
4     105    pinky     85
5     106     mano     85
6     107     achu     96

   reg_no    Name  marks
0     101   jency     98
1     102  beyana     63
2     103  chicku    100

   reg_no  Name  marks
5     106  mano     85
6     107  achu     96

(7, 3)

Index(['reg_no', 'Name', 'marks'], dtype='str')

0     98
1     63
2    100
3     35
4     85
5     85
6     96
Name: marks, dtype: int64

0      jency
1     beyana
2     chicku
3    manisha
4      pinky
5       mano
6       achu
Name: Name, dtype: str